"""One-shot cleanup for the scholar evaluation framework v2 rewrite.

Deletes legacy dossier artifacts that the old agent-based pipeline
wrote, preserving only data the new pipeline can either reuse
(`profile.json`, `papers.json`, `events.jsonl`, `channels.json`,
`uploads/`, `agent_runs/`) or regenerate on the next bootstrap.

What it wipes, per scholar:
- `evaluations/` (old monolithic YYYY-MM-DD_full.json files)
- `reports/` (old legacy `.md` reports)
- `narrative.jsonl` (will be regenerated by narrative_synthesizer)
- `peer_group.jsonl` (will be regenerated by phase_classifier)
- `snapshot_log.jsonl` (forces bootstrap mode on next heartbeat)
- `red_flags.jsonl` (regenerated by red_flags_watch)
- `attributed_metrics.json` (regenerated from papers.json)

Not touched: `profile.json`, `papers.json`, `events.jsonl`,
`channels.json`, `uploads/`, `agent_runs/`.

Run manually: `python backend/scripts/wipe_legacy_dossiers.py`.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SCHOLARS_DIR = ROOT / "data" / "scholars"

LEGACY_DIRS = ["evaluations", "reports"]
LEGACY_FILES = [
    "narrative.jsonl",
    "peer_group.jsonl",
    "snapshot_log.jsonl",
    "red_flags.jsonl",
    "attributed_metrics.json",
]


def wipe_scholar(dossier: Path) -> tuple[int, int]:
    dirs_removed = 0
    files_removed = 0
    for d in LEGACY_DIRS:
        p = dossier / d
        if p.exists() and p.is_dir():
            shutil.rmtree(p)
            dirs_removed += 1
    for f in LEGACY_FILES:
        p = dossier / f
        if p.exists() and p.is_file():
            p.unlink()
            files_removed += 1
    return dirs_removed, files_removed


def main() -> int:
    if not SCHOLARS_DIR.exists():
        print(f"No scholar data at {SCHOLARS_DIR}; nothing to do.")
        return 0

    scholars = [p for p in SCHOLARS_DIR.iterdir() if p.is_dir()]
    if not scholars:
        print("No scholar dossiers found.")
        return 0

    print(f"Wiping legacy artifacts for {len(scholars)} scholars under {SCHOLARS_DIR}")
    total_dirs = total_files = 0
    for s in scholars:
        d, f = wipe_scholar(s)
        total_dirs += d
        total_files += f
        if d or f:
            print(f"  {s.name}: removed {d} dirs, {f} files")
    print(f"Done. Removed {total_dirs} directories and {total_files} files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
